USE [master]
GO
/****** Object:  Database [MegaMinds]    Script Date: 20-04-2026 04:57:24 PM ******/
CREATE DATABASE [MegaMinds]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MegaMinds', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MegaMinds.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MegaMinds_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MegaMinds_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [MegaMinds] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MegaMinds].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MegaMinds] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MegaMinds] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MegaMinds] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MegaMinds] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MegaMinds] SET ARITHABORT OFF 
GO
ALTER DATABASE [MegaMinds] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [MegaMinds] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MegaMinds] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MegaMinds] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MegaMinds] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MegaMinds] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MegaMinds] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MegaMinds] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MegaMinds] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MegaMinds] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MegaMinds] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MegaMinds] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MegaMinds] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MegaMinds] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MegaMinds] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MegaMinds] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MegaMinds] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MegaMinds] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MegaMinds] SET  MULTI_USER 
GO
ALTER DATABASE [MegaMinds] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MegaMinds] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MegaMinds] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MegaMinds] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MegaMinds] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MegaMinds] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MegaMinds] SET QUERY_STORE = ON
GO
ALTER DATABASE [MegaMinds] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [MegaMinds]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 20-04-2026 04:57:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 20-04-2026 04:57:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SubCategories]    Script Date: 20-04-2026 04:57:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SubCategories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CategoryId] [int] NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_SubCategories] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserCategories]    Script Date: 20-04-2026 04:57:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserCategories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[CategoryId] [int] NOT NULL,
 CONSTRAINT [PK_UserCategories] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 20-04-2026 04:57:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Phone] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[IsAdmin] [bit] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_SubCategories_CategoryId]    Script Date: 20-04-2026 04:57:25 PM ******/
CREATE NONCLUSTERED INDEX [IX_SubCategories_CategoryId] ON [dbo].[SubCategories]
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserCategories_CategoryId]    Script Date: 20-04-2026 04:57:25 PM ******/
CREATE NONCLUSTERED INDEX [IX_UserCategories_CategoryId] ON [dbo].[UserCategories]
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserCategories_UserId]    Script Date: 20-04-2026 04:57:25 PM ******/
CREATE NONCLUSTERED INDEX [IX_UserCategories_UserId] ON [dbo].[UserCategories]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SubCategories]  WITH CHECK ADD  CONSTRAINT [FK_SubCategories_Categories_CategoryId] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SubCategories] CHECK CONSTRAINT [FK_SubCategories_Categories_CategoryId]
GO
ALTER TABLE [dbo].[UserCategories]  WITH CHECK ADD  CONSTRAINT [FK_UserCategories_Categories_CategoryId] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserCategories] CHECK CONSTRAINT [FK_UserCategories_Categories_CategoryId]
GO
ALTER TABLE [dbo].[UserCategories]  WITH CHECK ADD  CONSTRAINT [FK_UserCategories_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserCategories] CHECK CONSTRAINT [FK_UserCategories_Users_UserId]
GO
USE [master]
GO
ALTER DATABASE [MegaMinds] SET  READ_WRITE 
GO
